# Generated by Django 5.2.14 on 2026-05-12 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('gitLink', models.CharField(max_length=100)),
                ('linkedIn', models.CharField(max_length=100)),
                ('professionSummary', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
