# Generated by Django 4.2.3 on 2026-05-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildresume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EductaionDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('edu_from', models.DateField()),
                ('edu_to', models.DateField()),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.IntegerField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
