# Generated by Django 4.2.3 on 2026-05-13 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildresume', '0002_eductaiondeatils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EductaionDeatils',
            new_name='EductaionDetails',
        ),
        migrations.RenameModel(
            old_name='PersonalDeatils',
            new_name='PersonalDetails',
        ),
    ]
