# Generated by Django 4.2.3 on 2026-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0006_projectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eductaiondetails',
            name='cgpa',
            field=models.FloatField(max_length=3),
        ),
    ]
