# Generated by Django 4.2.3 on 2026-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0007_alter_eductaiondetails_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='eductaiondetails',
            name='Degree',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='eductaiondetails',
            name='location',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
