# Generated by Django 4.2.3 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0008_eductaiondetails_degree_eductaiondetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondetails',
            name='exp_to',
            field=models.CharField(max_length=20),
        ),
    ]
