# Generated by Django 4.2.3 on 2026-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0009_alter_professiondetails_exp_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiondetails',
            name='role',
            field=models.CharField(default='Null', max_length=40),
        ),
    ]
