# Generated by Django 4.2.3 on 2026-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0010_professiondetails_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professiondetails',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
