# Generated by Django 4.2.3 on 2026-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildresume', '0011_alter_professiondetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
